/*
 * ST7701 parallel-RGB PIO program for the Pimoroni Presto.
 *
 * Assembled with pioasm from drivers/st7701/st7701_parallel.pio in the
 * Pimoroni Presto firmware (github.com/pimoroni/presto).
 *
 * Copyright (c) 2024 Pimoroni Ltd
 * SPDX-License-Identifier: MIT
 */

/* ---------------------------------------------------------------- */
/* This file is autogenerated by pioasm version 2.2.0; do not edit!  */
/* ---------------------------------------------------------------- */

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

/* --------------- */
/* st7701_parallel */
/* --------------- */

#define st7701_parallel_wrap_target 0
#define st7701_parallel_wrap 7
#define st7701_parallel_pio_version 0

static const uint16_t st7701_parallel_program_instructions[] = {
            /*     .wrap_target */
    0xb022, /*  0: mov    x, y            side 1     */
    0x30c4, /*  1: wait   1 irq, 4        side 1     */
    0x70c0, /*  2: out    isr, 32         side 1     */
    0xb116, /*  3: mov    pins, ::isr     side 1 [1] */
    0x5170, /*  4: in     null, 16        side 1 [1] */
    0xb116, /*  5: mov    pins, ::isr     side 1 [1] */
    0x1042, /*  6: jmp    x--, 2          side 1     */
    0xb003, /*  7: mov    pins, null      side 1     */
            /*     .wrap */
};

#if !PICO_NO_HARDWARE
static const struct pio_program st7701_parallel_program = {
    .instructions = st7701_parallel_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = st7701_parallel_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config st7701_parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + st7701_parallel_wrap_target, offset + st7701_parallel_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
