/*
 * ST7701 sync-timing PIO program for the Pimoroni Presto.
 *
 * Assembled with pioasm from drivers/st7701/st7701_timing.pio in the
 * Pimoroni Presto firmware (github.com/pimoroni/presto).
 *
 * The timing state machine executes instruction words fed from its TX FIFO
 * (see the driver's timing ISR). Side-set is the pixel/dot clock.
 *
 * Copyright (c) 2024 Pimoroni Ltd
 * SPDX-License-Identifier: MIT
 */

/* ---------------------------------------------------------------- */
/* This file is autogenerated by pioasm version 2.2.0; do not edit!  */
/* ---------------------------------------------------------------- */

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

/* ------------- */
/* st7701_timing */
/* ------------- */

#define st7701_timing_wrap_target 0
#define st7701_timing_wrap 4
#define st7701_timing_pio_version 0

static const uint16_t st7701_timing_program_instructions[] = {
            /*     .wrap_target */
    0x6002, /*  0: out    pins, 2         side 0 */
    0x702e, /*  1: out    x, 14           side 1 */
    0xa042, /*  2: nop                    side 0 */
    0x1042, /*  3: jmp    x--, 2          side 1 */
    0x60f0, /*  4: out    exec, 16        side 0 */
            /*     .wrap */
};

#if !PICO_NO_HARDWARE
static const struct pio_program st7701_timing_program = {
    .instructions = st7701_timing_program_instructions,
    .length = 5,
    .origin = 0,
    .pio_version = st7701_timing_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config st7701_timing_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + st7701_timing_wrap_target, offset + st7701_timing_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
